name: ci

on: 
  push:
    branches: 
      - workflow
    paths:
      - '!**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: | 
         npm ci
         npm run build --if-present
      - name: upload build folder
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build/*
      - run: npm test -- --coverage
        env:
          CI: true


